version: '3.8'
services:

  postgres:
    image: postgres
    build:
      context: ./postgres_db
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - myNetwork
    volumes:
      - postgres:/var/lib/postgresql/data
    command: [ 'postgres', '-c', 'logging_collector=on' ]
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - myNetwork
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

volumes:
  postgres:


networks:
  myNetwork:
    driver: bridge
